name: Merge upstream branches
on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main  # 只有推送到 `main` 分支时才触发

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global credential.helper store
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/tanquan/bytebase.git tmp
          cd tmp
          git remote add upstream https://${{ secrets.PAT_TOKEN }}@github.com/bytebase/bytebase.git
          git fetch upstream
          git merge upstream/main
          git push origin main
